### ISSUE TITLE
Checklist for v0.5 submission

### ISSUE THREAD

**Issue by pyokagan** [CS2103AUG2016-T11-C4/main#182]
## Admin
* [x] Collation
* [x] **ABOUT ME NEEDS TO BE UPDATED**
* [ ] **TEST SCRIPT** (TOP PRIORITY) (Okay @nightism  will do it)

## User Guide

* [x] Commands need to be updated

@potatowagon  ???

## Developer Guide
* [x] Explain undo/redo
* [x] Explain OverloadParser / SubcommandParser (Diagrams already there, just need a few sentences each when I'm awake)
* [x] Update `Model` diagram to include `ReadOnlyModel`.
* [x] How `HelpCommandResult`, `ExitCommandResult` works
* [x]  consistent capitalisation in section headers 
* [x] use american spelling consistently 
* [x] Acknowledgements
* [x] Syntax highlighting for code

THAT should be all.

## Code
* [x] Fix "setdatadir" autocomplete: should remove the filename at the end :X (Actually, maybe just remove it, not important)
* [x] status bar taskbook location needs to be connected to Config's property.

**Comment by nightism** [comment]
@pyokagan I think I can help you do the undo/redo part.

**Comment by pyokagan** [comment]
@nightism (Y) gladly

**Comment by potatowagon** [comment]
mingyang has agreed to pass me the undo / redo part so he can focus on the test script. Userguide is almost done.

**Comment by potatowagon** [comment]
Userguide done, but Table of Content Links broken, i dont know how to fix

**Comment by potatowagon** [comment]
Undo redo implementation in dg doc done
